language: c
compiler: gcc

os: linux
sudo: false
dist: trusty

git:
  depth: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python-numpy
      - cmake

script:
  # PETSc: we use a cache to avoid rebuilding
  - if [ ! -f "petsc-stagbl/configure.log" ]; then git clone --recurse-submodules --depth=1 https://bitbucket.org/psanan/petsc -b psanan/stagbl-working-base petsc-stagbl; fi
  - cd petsc-stagbl
  - export PETSC_DIR=$PWD
  - export PETSC_ARCH=default-arch-gnu-debug
  - if [ ! -f "configure.log" ]; then ./configure --download-mpich --download-suitesparse --download-metis --download-parmetis --download-superlu_dist --download-mumps --download-scalapack ; fi
  - if [ ! -f "make.log" ]; then make all; fi
  - make check
  - cd ..
  # Configure StagBL
  - ./configure.py
  - export STAGBL_DIR=$PWD
  - export STAGBL_ARCH=$PETSC_ARCH
  # Make StagBL (no -j)
  - make -C $STAGBL_ARCH
  - make -C $STAGBL_ARCH demos
  # Run tests
  - cd tests
  - export SCIATH_CONF=../${PETSC_ARCH}/pth.conf
  - ./run_tests.py -w $SCIATH_CONF -d # default config
  - sed -i "/mpiLaunch=.*/d" $SCIATH_CONF
  - echo "mpiLaunch=$PETSC_DIR/$PETSC_ARCH/bin/mpiexec -np <ranks>" >> $SCIATH_CONF
  - ./run_tests.py -w $SCIATH_CONF -f # return error code

cache:
  directories:
    - petsc-stagbl
