language: c
compiler: gcc

os: linux
sudo: false
dist: trusty

git:
  depth: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - python-numpy
      - cmake

script:
  # PETSc: we use a cache to avoid rebuilding
  - if [ ! -f "petsc-3.12.1/configure.log" ]; then curl -O http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.12.1.tar.gz && tar zxvf petsc-lite-3.12.1.tar.gz; fi
  - cd petsc-3.12.1
  - export PETSC_DIR=$PWD
  - export PETSC_ARCH=default-arch-gnu-debug
  - if [ ! -f "configure.log" ]; then ./configure --download-mpich --download-suitesparse --download-metis --download-parmetis --download-mumps --download-scalapack --with-shared-libraries=0; fi
  - if [ ! -f "make.log" ]; then make all; fi
  - make check
  - cd ..
  # Test harness from submodule
  - git submodule init && git submodule update --recursive
  # Configure StagBL
  - ./configure.py
  - export STAGBL_DIR=$PWD
  - export STAGBL_ARCH=$PETSC_ARCH
  # Make StagBL (no -j)
  - make -C $STAGBL_ARCH
  - make -C $STAGBL_ARCH demos
  # Run tests
  - cd tests
  - export SCIATH_CONF=../${PETSC_ARCH}/pth.conf
  - ./run_tests.py -w $SCIATH_CONF -d # default config
  - sed -i "/mpiLaunch=.*/d" $SCIATH_CONF
  - echo "mpiLaunch=$PETSC_DIR/$PETSC_ARCH/bin/mpiexec -np <ranks>" >> $SCIATH_CONF
  - ./run_tests.py -w $SCIATH_CONF -f # return error code

cache:
  directories:
    - petsc-3.12.1
