pipelines:
  branches:
    master: &default-step
      - step:
          caches:
            - petsc-3-11-0
          script:
            # Packages
            - sudo apt-get update
            - sudo apt-get --fix-missing -yq --no-install-suggests --no-install-recommends --force-yes install gfortran libblas-dev liblapack-dev python-numpy bison
            # PETSc: we use a cache to avoid rebuilding, checking if configure.log exists
            - if [ ! -f "petsc-3.11.0/configure.log" ]; then curl -O http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.11.0.tar.gz && tar zxvf petsc-lite-3.11.0.tar.gz; fi
            - cd petsc-3.11.0
            - export PETSC_DIR=$PWD
            - export PETSC_ARCH=default-arch-gnu-debug
            - if [ ! -f "configure.log" ]; then ./configure --download-mpich --download-suitesparse --download-metis --download-parmetis --download-ptscotch --download-mumps --with-shared-libraries=0; fi
            - if [ ! -f "make.log" ]; then make all; fi
            - make check
            - cd ..
            # Clone test harness
            - git clone https://bitbucket.org/dmay/pythontestharness
            # Configure StagBL
            - ./configure.py
            - export STAGBL_DIR=$PWD
            - export STAGBL_ARCH=$PETSC_ARCH
            # Make StagBL (no -j)
            - make -C $STAGBL_ARCH
            - make -C $STAGBL_ARCH demos
            # Run tests
            - cd tests
            - export PTH_CONF=../${PETSC_ARCH}/pth.conf
            - ./runTests.py -w $PTH_CONF -d # default config
            - sed -i "/mpiLaunch=.*/d" $PTH_CONF
            - echo "mpiLaunch=$PETSC_DIR/$PETSC_ARCH/bin/mpiexec -np <ranks>" >> $PTH_CONF
            - ./runTests.py -w $PTH_CONF -f # return error code
definitions:
   caches:
      petsc-3-11-0: petsc-3.11.0
